<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru" dir="ltr">
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
		<script type="text/javascript" src="<?php echo $this->baseUrl().'http://maps.google.com/maps/api/js?sensor=true&language=eng'?>"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl().'/jquery/js/jquery-1.7.1.min.js'?>"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl().'/jquery/js/jquery-ui-1.8.18.custom.min.js'?>"></script>
		<script src="/js/redactor/redactor.js"></script>
		<link rel="stylesheet" href="/js/redactor/css/redactor.css" />
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/admin.css')
								->prependStylesheet($this->baseUrl().'/css/bootstrap.css')
								->prependStylesheet($this->baseUrl().'/css/jquery.multiselect.css')
								->prependStylesheet($this->baseUrl().'/css/jquery.multiselect.filter.css')
								->prependStylesheet($this->baseUrl().'/css/ui-lightness/jquery-ui-1.8.17.custom.css')
								->prependStylesheet($this->baseUrl().'/jquery/timepicker/css/timePicker.css'); ?>
	<?php echo $this->headScript()->appendFile($this->baseUrl().'/jquery/timepicker/js/jquery.timePicker.min.js')
								->appendFile($this->baseUrl().'/js/jquery.fancybox.js')
								->appendFile($this->baseUrl().'/js/jquery.multiselect.js')
								->appendFile($this->baseUrl().'/js/jquery.multiselect.filter.js')
								->appendFile($this->baseUrl().'/js/jvalidate.js')
								->appendFile($this->baseUrl().'/js/common.js'); ?>
	<?php echo $this->headMeta()?>
	<?php echo $this->headTitle()?>
	
	
	<script type="text/javascript">
   		var SYS = {
				siteUrl: '<?php echo $this->baseUrl()?>'
   		   	}
			
		var LANG  = <?php echo json_encode($this->translate->getAdapter()->getMessages()); ?>;
		
		function translate(text)
		{
			if(LANG[text]) {
				return LANG[text];
			} else {
				return text;
			}
		}
		
	</script>
</head>
<body>
	<div id="conteiner">
		<div class="content">	
			<a href="<?php echo $this->baseUrl()?>/<?php echo $_SESSION['lang']?>/main"><?php echo $this->translate('To the site')?></a>
			<div class="row">
				<div class="span2 dashboard-menu">
					<div class="span2 dashboard-menu">
						<ul>
							<li class="dahsboard-users"><a href="<?php echo $this->baseUrl()?>/<?php echo $_SESSION['lang']?>/users/manageuser">Users</a></li>
							<li class="dahsboard-events"><a href="<?php echo $this->baseUrl()?>/<?php echo $_SESSION['lang']?>/main/managelistings">Listings</a></li>
							<li class="dahsboard-events"><a href="<?php echo $this->baseUrl()?>/<?php echo $_SESSION['lang']?>/admin/managegrapes">Grapes</a></li>
							<li class="dahsboard-events"><a href="<?php echo $this->baseUrl()?>/<?php echo $_SESSION['lang']?>/admin/managecountries">Countries</a></li>
							<li class="dahsboard-events"><a href="<?php echo $this->baseUrl()?>/<?php echo $_SESSION['lang']?>/admin/manageregions">Wine Regions</a></li>
							<li class="dahsboard-events"><a href="<?php echo $this->baseUrl()?>/<?php echo $_SESSION['lang']?>/main/managechanges">Listings Changes</a></li>
							<li class="dahsboard-events"><a href="<?php echo $this->baseUrl()?>/<?php echo $_SESSION['lang']?>/admin/managecontacts">Contact Us</a></li>
							<li class="dahsboard-events"><a href="<?php echo $this->baseUrl()?>/<?php echo $_SESSION['lang']?>/admin/managepages">Static Pages</a></li>
							<li class="dahsboard-events"><a href="<?php echo $this->baseUrl()?>/<?php echo $_SESSION['lang']?>/admin/manageseo">SEO</a></li>
							<li class="dahsboard-events"><a href="<?php echo $this->baseUrl()?>/<?php echo $_SESSION['lang']?>/admin/managetemplates">Emails Templates</a></li>
							<li class="dahsboard-events"><a href="<?php echo $this->baseUrl()?>/<?php echo $_SESSION['lang']?>/admin/managerequests">Requests Users Holiday</a></li>
						</ul>	
					</div>		   
				</div>
				<div class="span13 dashboard-content">
					<?php echo $this->layout()->content; ?>
				</div>
			</div>
		</div>
	</div>
</body>
</html>