<?php if($this->form):?>
	<h2 class="title borderBottom noBg"><?php echo $this->message ?></h2>
	<div class="descr-forgot">
		<h4><span class="greenText"><?php echo $this->translate('To activate your account, enter your password and repeat it')?>.</span></h4> 
	</div>
	<form action="" method="post" id="active" class="jNice form profile">
		<div class="flw borderBottom formSection">
			<div class="oneLine">
				<label for="password"><?php echo $this->translate('Password')?>*:</label>
				<div class="wrapperInput">
					<div class="rounded tl"></div>
					<div class="rounded tr"></div>
					<div class="rounded br"></div>
					<div class="rounded bl"></div>
					<?php echo $this->form->password;?>
				</div>
				<div class="helpWrapper"><span class="helpInfo"><?php echo $this->translate('Please enter your password')?></span></div>
			</div>
			<div class="oneLine">
				<label for="confirm"><?php echo $this->translate('Password Confirm')?>*:</label>
				<div class="wrapperInput">
					<div class="rounded tl"></div>
					<div class="rounded tr"></div>
					<div class="rounded br"></div>
					<div class="rounded bl"></div>
					<?php echo $this->form->repassword;?>
				</div>
				<div class="helpWrapper"><span class="helpInfo"><?php echo $this->translate('Please repeat your password')?></span></div>
			</div>
		</div>
		<div class="textAlignCenter">
			<?php echo $this->form->register;?>
		</div>	
	</form>
<?php endif;?>
<div class = "errors">
	<?php echo $this->message;?>
</div>