<h2 class="title borderBottom noBg"><?php echo $this->message ?></h2>
<form action="<?php echo $this->form->getAction()?>" method="post" id="change_password" class="jNice form profile">
	<div class="flw borderBottom formSection">
		<div class="oneLine">
			<label for="password"><?php echo $this->translate('Password')?>*:</label>
			<div class="wrapperInput">
				<div class="rounded tl"></div>
				<div class="rounded tr"></div>
				<div class="rounded br"></div>
				<div class="rounded bl"></div>
				<?php echo $this->form->password;?>
			</div>
			<div class="helpWrapper"><span class="helpInfo"><?php echo $this->translate('Please enter your new password')?></span></div>
		</div>
		<div class="oneLine">
			<label for="confirm"><?php echo $this->translate('Password Confirm')?>*:</label>
			<div class="wrapperInput">
				<div class="rounded tl"></div>
				<div class="rounded tr"></div>
				<div class="rounded br"></div>
				<div class="rounded bl"></div>
				<?php echo $this->form->repassword;?>
			</div>
			<div class="helpWrapper"><span class="helpInfo"><?php echo $this->translate('Please repeat your new password')?></span></div>
		</div>
	</div>
	<div class="textAlignCenter">
		<input type="submit" class="redSubmitBg" value="<?php echo $this->translate('Change Password')?>">
		<a href="<?php echo $this->baseUrl()?>/<?php echo $_SESSION['lang'] . '/users/editprofile'?>" class="grayLink"><?php echo $this->translate('Cancel')?></a>
	</div>	
</form>