<h2 class="title borderBottom noBg"><?php echo $this->message ?></h2>
<div class="descr-forgot">
	<h4><span class="greenText"><?php echo $this->translate('Please enter your email address below and we will send you a new one.')?>.</span></h4> 
	<h4><span class="greenText"><?php echo $this->translate('Remember to update your password when you have logged in successfully.')?>.</span></h4>
</div>
<form action="<?php echo $this->form->getAction()?>" method="post" id="forgot_password" class="jNice form profile">
	<div class="flw borderBottom formSection">
		<div class="oneLine">
			<label for="email">Enter your email address:</label>
			<div class="wrapperInput">
				<div class="rounded tl"></div>
				<div class="rounded tr"></div>
				<div class="rounded br"></div>
				<div class="rounded bl"></div>
				<?php echo $this->form->email?>
			</div>
			<div class="helpWrapper"><span class="helpInfo"><?php echo $this->translate('Please enter your email address')?></span></div>
		</div>
	</div>	
	<div class="textAlignCenter">
		<input type="submit" class="redSubmitBg" value="<?php echo $this->translate('Send New Password')?>">
		<a href="<?php echo $this->baseUrl()?>/<?php echo $_SESSION['lang'] . '/main'?>" class="grayLink"><?php echo $this->translate('Cancel')?></a>
	</div>
</form>