<div id="view-content">
	<h2><?php echo $this->message ?></h2>
	<?php if(count($this->paginator)) :?>
		<table class="table table-bordered table-striped">
			<thead>
				<tr>
					<th class="span1">Username</th>
					<th class="span1">Firstname</th>
					<th class="">Email</th>
					<th class="option-th span3">Options</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach($this->paginator as $user):?>
				<tr>
					<td><?php echo $this->escape($user['name']) ?></td>
					<td><?php echo $this->escape($user['firstname']) ?></td>
					<td><?php echo $this->escape($user['email']) ?></td>
					<td class="options-td">
						<a href="<?php echo $this->baseUrl() . '/' . $_SESSION['lang']?>/users/edituser/id/<?php echo $user['id']?>">Edit</a> - 
						<a class="remove" href="#" rel="user_<?php echo $user['id']?>">Delete</a>
				</tr>
			<?php endforeach;?>
			</tbody>
		</table>
	<?php echo $this->paginationControl($this->paginator, 'Sliding', 'users/pagination_users.phtml'); ?>	
	<?php else:?>
		<p>No Users</p>
	<?php endif;?>	
	<b><a href="<?php echo $this->baseUrl() . '/' . $_SESSION['lang']?>/users/adduser">Add new user</a></b>
</div>