<div class="content">
<!--  <h2><?php // echo $this->message ?></h2>-->

  <?php if (isset($this->exception)): ?>
  <h1 style="font-size: 40px;"><?php echo $this->translate('404 Page Not Found')?></h1>
<!--  <h3>Exception information:</h3>-->
  <h3 style="font-size: 20px; margin-top: 15px;"><?php echo $this->exception->getMessage() ?></h3>
<!--
  <h3>Stack trace:</h3>
  <pre><?php // echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php // echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>-->

  <?php endif ?>
</div>