<form action="<?php echo $this->form->getAction()?>" method="post" id="contactus" class="jNice form contact">
	<h2 class="title borderBottom noBg"><?php echo $this->translate($this->message) ?></h2>
	<div class="flw borderBottom formSection">
		<?php if(Zend_Auth::getInstance()->hasIdentity()):?>
			<?php $user = Zend_Auth::getInstance()->getIdentity();?>
		<?php endif;?>		
		<div class="oneLine">
			<label for="name"><?php echo $this->translate('Name')?>:</label>
			<div class="wrapperInput">
				<div class="rounded tl"></div>
				<div class="rounded tr"></div>
				<div class="rounded br"></div>
				<div class="rounded bl"></div>
				<?php echo $this->form->getElement('name')->setAttrib('class', 'inputBox')->setValue(!empty($user) ? $user->name : '') ?>
			</div>
		</div>
		<div class="oneLine">
			<label for="email"><?php echo $this->translate('E-mail Address')?>*:</label>
			<div class="wrapperInput">
				<div class="rounded tl"></div>
				<div class="rounded tr"></div>
				<div class="rounded br"></div>
				<div class="rounded bl"></div>
				<?php echo $this->form->email->setAttrib('class', 'inputBox')->setValue(!empty($user) ? $user->email : '') ?>
			</div>
		</div>
		<div class="oneLine">
			<label for="enquiry"><?php echo $this->translate('Subject')?>*:</label>
			<div class="wrapperInput">
				<div class="rounded tl"></div>
				<div class="rounded tr"></div>
				<div class="rounded br"></div>
				<div class="rounded bl"></div>
				<?php echo $this->form->subject->setAttrib('class', 'inputBox') ?>
			</div>
		</div>
		<div class="oneLine">
			<label for="comment"><?php echo $this->translate('Your Comment/Enquiry')?>*:</label>
			<div class="wrapperInput texarea">
				<div class="rounded tl"></div>
				<div class="rounded tr"></div>
				<div class="rounded br"></div>
				<div class="rounded bl"></div>
				<?php echo $this->form->comment->setAttrib('class', 'inputBox') ?>
			</div>
		</div>
	</div>
	<div class="flw borderBottom formSection">
		<h5 class="sectionTitle"><?php echo $this->translate('Captcha')?></h5>
		<span class="text"><?php echo $this->translate('This question is for testing whether you are a human visitor and to prevent automated spam submisions')?>.</span>
		<?php echo $this->form->captcha ?>
	</div>
	<div class="textAlignCenter"><?php echo $this->form->submit ?></div>
</form>	