<script>
	var loc_y = <?php echo $this->region->loc_y?>;
	var loc_z = <?php echo $this->region->loc_z?>;
</script>
<div class="articleWrapper">
	<div class="content">
		<ul class="breadcrumbs">
			<li><?php echo $this->region->continent_name?></li>
			<li class="sep"></li>
			<li><a href="<?php echo $this->baseUrl() . '/' . $_SESSION['lang']?>/main/view-country/<?php echo $this->region->country_alias?>"><?php echo $this->region->country_name?></a></li>
			<li class="sep"></li>
			<li><?php echo $this->region->name?></li>
		</ul>
		<div class="borderBottom flw">
			<h2 class="title noBg"><?php echo $this->translate('Wine Tours in')?>: <?php echo $this->region->name?></h2>
			<?php $reg_mod = new Application_Model_Assregions();?>
			<?php if($reg_mod->isExistVineyard($this->region->id)) :?>
				<a href="<?php echo $this->baseUrl() . '/' . $_SESSION['lang']?>/search/list?type%5Bvin%5D=vin&amp;status%5Bverif%5D=verif&amp;status%5Bunver%5D=unver&amp;status%5Bclaim%5D=claim&amp;continent=<?php echo $this->region->continent_id?>&amp;country=<?php echo $this->region->country?>&amp;ass_region=<?php echo $this->region->id?>" class="redSubmitBg findInThisRegion"><?php echo $this->translate('Find Vineyards in this region')?></a>
			<?php endif;?>
		</div>
		<div class="articleBox">
			<div class="oneLine locations"><span class="greenText"><?php echo $this->translate('Associated Country')?>:</span><span><?php echo $this->region->country_name?></span></div>
				<article class="borderBottom" style="min-height: 200px;">
					<h4 class="titleArticle"><?php echo $this->translate('Summary')?></h4>
					<?php if(!empty($this->region->description)) :?>
						<p><?php echo $this->region->description?></p>
					<?php else:?>
						<p><?php echo $this->translate('No summary')?></p>
					<?php endif;?>
				</article>
			<div class="links">
				<?php $grapes = unserialize($this->region->grapes);?>
				<?php if(!empty($gr)) :?>
					<div class="oneLine">
						<span class="greenText"><?php echo $this->translate('Principle Grapes')?>:</span>
						<ul>
							<?php foreach($grapes as $grape) :?>
								<li><a href="#"><?php echo $grape?></a></li>
								<?php if($grape != $grapes[count($grapes)-1]) :?>
									<li class="sep"></li>
								<?php endif;?>
							<?php endforeach;?>
						</ul>
					</div>
				<?php endif;?>
				<div class="oneLine">
					<span class="greenText"><?php echo $this->translate('Parent Region')?>:</span>
					<ul>
						<?php if($this->region->pid != 0) :?>
							<?php $reg_mod = new Application_Model_Assregions();?>
							<?php $par_reg = $reg_mod->getRegionById($this->region->pid)?>
							<?php if(!empty($par_reg)) :?>
								<li><a href="<?php echo $this->baseUrl() . '/' . $_SESSION['lang']?>/main/view-region/<?php echo $par_reg->country_alias?>/<?php echo main::getParent1($par_reg->alias)?>" class="borderRight"><?php echo $par_reg->name?></a></li>
							<?php else:?>
								<li><?php echo $this->translate('None')?></li>
							<?php endif;?>
						<?php else:?>
							<li><?php echo $this->translate('None')?></li>
						<?php endif;?>
					</ul>
				</div>
				<div class="oneLine">
					<span class="greenText"><?php echo $this->translate('Associated Sub Regions')?>:</span>
					<ul>
					<?php $reg_mod = new Application_Model_Assregions();?>
					<?php $sub_regs = $reg_mod->getAssRegionsByPidId($this->region->id)?>
					<?php if(!empty($sub_regs[0])) :?>
						<?php $i = 0;?>
						<?php foreach($sub_regs as $sub_reg) :?>
							<li><a href="<?php echo $this->baseUrl() . '/' . $_SESSION['lang']?>/main/view-region/<?php echo $sub_reg->country_alias?>/<?php echo main::getParent1($sub_reg->alias)?>" class="borderRight"><?php echo $sub_reg->name?></a></li>
							<?php if($i != count($sub_regs) - 1) :?>
								<li class="sep"></li>
							<?php endif;?>
						<?php $i++?>		
						<?php endforeach;?>
					<?php else:?>
						<li><?php echo $this->translate('None')?></li>
					<?php endif;?>						
					</ul>
				</div>
			</div>
			<?php if(!empty($this->region->links)) :?>
				<div class="relatedLinks">
					<div class="oneLine">
						<span class="greenText"><?php echo $this->translate('Related Links')?>:</span>
						<ul>
							<?php $alt_texts = unserialize($this->region->texts)?>
							<?php foreach(unserialize($this->region->links) as $key => $link) :?>
								<li><a href="<?php echo $link?>"><?php echo !empty($alt_texts[$key]) ? $alt_texts[$key] : $link?></a></li>
							<?php endforeach;?>
						</ul>
					</div>
				</div>
			<?php endif;?>			
		</div>
	</div>
	<aside>
		<?php echo $this->render('holiday_organization/holiday_box.phtml');?>
		<div class="mapBox">
			<h3 class="title noBg"><?php echo $this->translate('Location of Region')?></h3>
			<div id="view_region" style="width: 358px; height: 350px;"></div>
			<div class="shadow"></div>
		</div>
		<?php if(!empty($this->region->image)) :?>
			<div class="mapBox region">
				<h3 class="title noBg"><?php echo $this->region->name?> <?php echo $this->translate('Wine Region')?></h3>
				<div class="map">
					<img src="/images/region/<?php echo $this->region->image?>" alt="<?php echo $this->alt?>" title="<?php echo $this->img?>">
				</div>
				<div class="shadow"></div>
			</div>
		<?php endif;?>
		<?php if(!empty($this->region->acknowledgements)) :?>
			<div class="grayBox acknowledgments">
				<h3 class="title"><?php echo $this->translate('Acknowledgments')?></h3>
				<ul>
					<li><?php echo $this->region->acknowledgements?></li>
				</ul>
				<div class="shadow"></div>
			</div>
		<?php endif;?>
	</aside>	
</div>
<?php echo $this->render('holiday_organization/holiday_form.phtml');?>