<div id="view-content">
	<h2><?php echo $this->message ?></h2>
	<b><a href="<?php echo $this->baseUrl() . '/' . $_SESSION['lang']?>/admin/addregion">Add New Wine Region</a></b>
	<form name="country_filter" action="<?php echo $this->baseUrl() . '/' . $_SESSION['lang']?>/admin/manageregions" id="country_filter" method="post">
		<h4>Filter By Country:</h4>
		<select name="countries" id="countries">
			<option value="all" <?php echo $this->country == 'all' ? 'selected' : ''?>>All Countries</option>
			<?php foreach($this->countries as $country) :?>
				<option value="<?php echo $country->alias?>" <?php echo $this->country == $country->alias ? 'selected' : ''?>><?php echo $country->name_en?></option>
			<?php endforeach;?>
		</select>
	</form>
	<?php if(count($this->paginator)) :?>
		<table class="table table-bordered table-striped">
			<thead>
				<tr>
					<th class="span1">Region Name</th>
					<th class="span1">Region Localname</th>
					<th class="">Country</th>
					<th class="">Data last change</th>
					<th class="">Partners</th>
					<th class="option-th span3">Options</th>
				</tr>
			</thead>
			<tbody>
			<?php $con_mod = new Application_Model_Countries();?>
			<?php $part_mod = new Application_Model_Partners();?>
			<?php foreach($this->paginator as $region):?>
				<tr>
					<td><?php echo $this->escape($region['name']) ?></td>
					<td><?php echo $this->escape($region['local_name']) ?></td>
					<td><?php echo $con_mod->getCountryByCode($region['country'])->name_en ?></td>
					<td><?php echo $this->escape(date("d.m.Y H:i:s",$region['update'])) ?></td>
					<td>
						<?php foreach($part_mod->getRegionUsers($region['id']) as $partner) :?>
						<a href="<?php echo $this->baseUrl() . '/' . $_SESSION['lang']?>/users/edituser/id/<?php echo $partner->id?>"><p><?php echo $partner->name?></p></a>
						<?php endforeach;?>
					</td>
					<td class="options-td">
						<a href="<?php echo $this->baseUrl() . '/' . $_SESSION['lang']?>/admin/editregion/<?php echo main::getParent1($region['alias'])?>">Edit</a> - 
						<a class="remove" href="#" rel="region_<?php echo $region['id']?>">Delete</a>
					</td>
				</tr>
			<?php endforeach;?>
			</tbody>
		</table>
	<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'admin/pagination_regions.phtml',
				array('country'=>$this->country)); ?>
	<?php else:?>
		<p>No Wine Regions</p>
	<?php endif;?>
</div>