<div id="view-content">
	<h2><?php echo $this->message ?></h2>
	<?php if(!empty($this->pages[0])) :?>
		<table class="table table-bordered table-striped">
			<thead>
				<tr>
					<th class="span2">Name</th>
					<th class="span2">Options</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach($this->pages as $page):?>
				<tr>
					<td><?php echo $this->escape($page->name) ?></td>
					<td class="span2">
						<a href="<?php echo $this->baseUrl()?>/<?php echo $_SESSION['lang']?>/admin/editpage/<?php echo $page->id?>">Edit Content</a>
					</td>
				</tr>
			<?php endforeach;?>
			</tbody>
		</table>
	<?php else:?>
		<p>No Pages</p>
	<?php endif;?>
</div>