<?php if ($this->pageCount) :?>
	<div class="paginationControl">
<!-- First page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->first)); ?>">
    First
  </a> 
<?php else: ?>
  <span class="disabled">First</span> 
<?php endif; ?>
		<?php if (isset($this->previous)) :?>
			<a href="<?php echo $this->url(array('country' => $this->country, 'page' => $this->previous)); ?>">&lt;</a> |
		<?php else :?>
			<span class="disabled">&lt;</span> |
		<?php endif;?>
		<?php foreach ($this->pagesInRange as $page) :?>
			<?php if ($page != $this->current) :?>
				<a href="<?php echo $this->url(array('country' => $this->country, 'page' => $page)); ?>"><?php echo $page; ?></a> |
			<?php else :?>
				<?php echo $page; ?> |
			<?php endif;?>
		<?php endforeach;?>  
		<?php if (isset($this->next)) :?>
			<a href="<?php echo $this->url(array('country' => $this->country, 'page' => $this->next)); ?>">&gt;</a>
		<?php else :?>
			<span class="disabled">&gt;</span>
		<?php endif;?>
<!-- Last page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->last)); ?>">
    Last
  </a>
<?php else: ?>
  <span class="disabled">Last</span>
<?php endif; ?>			
	</div>
<?php endif;?>