<?php if ($this->pageCount) :?>
	<div class="paginationControl">
		<?php if (isset($this->previous)) :?>
			<a href="<?php echo $this->url(array('date' => $this->this->date, 'type' => $this->type, 'page' => $this->previous)); ?>">&lt;</a> |
		<?php else :?>
			<span class="disabled">&lt;</span> |
		<?php endif;?>
		<?php foreach ($this->pagesInRange as $page) :?>
			<?php if ($page != $this->current) :?>
				<a href="<?php echo $this->url(array('date' => $this->date, 'type' => $this->type, 'page' => $page)); ?>"><?php echo $page; ?></a> |
			<?php else :?>
				<?php echo $page; ?> |
			<?php endif;?>
		<?php endforeach;?>  
		<?php if (isset($this->next)) :?>
			<a href="<?php echo $this->url(array('date' => $this->date, 'type' => $this->type, 'page' => $this->next)); ?>">&gt;</a>
		<?php else :?>
			<span class="disabled">&gt;</span>
		<?php endif;?>
	</div>
<?php endif;?>